#!/bin/bash
set -euo pipefail

read -rp "USERNAME: " USERNAME
while true; do
    read -rsp "PASSWD: " PASSWORD
    echo
    read -rsp "CONFIRM PASSWD: " PASSWORD_CONFIRM
    echo
    if [ "$PASSWORD" = "$PASSWORD_CONFIRM" ]; then
        break
    else
        echo "Passwords do not match. Please try again."
    fi
done

reflector -c "NL" -p https --age 4 --latest 15 --save /etc/pacman.d/mirrorlist
sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf

cryptsetup luksFormat --batch-mode /dev/nvme0n1p2 
cryptsetup luksOpen /dev/nvme0n1p2 croot

mkfs.fat /dev/nvme0n1p1
mkfs.xfs /dev/mapper/croot

PART_UUID=$(blkid -s UUID -o value "/dev/nvme0n1p2")

mount /dev/mapper/croot /mnt
mount -o umask=0077 -m /dev/nvme0n1p1 /mnt/boot

pacstrap -K /mnt base

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt bash <<😺
set -e

pacman -S --noconfirm mkinitcpio

sed -i 's/^HOOKS=.*/HOOKS=(base udev autodetect modconf keyboard block encrypt filesystems)/' /etc/mkinitcpio.conf

sed -i 's/^SigLevel.*/SigLevel = Never/' /etc/pacman.conf
sed -i 's/^LocalFileSigLevel.*/LocalFileSigLevel = Never/' /etc/pacman.conf

pacman -S --needed --noconfirm linux-zen linux-firmware-intel intel-ucode networkmanager sudo vim git stow hyprland waybar firefox github-cli 

echo "root:$PASSWORD" | chpasswd

useradd -mG wheel $USERNAME
echo "$USERNAME:$PASSWORD" | chpasswd
echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers

sed -i 's/fmask=0022,dmask=0022/umask=0077/' /etc/fstab

bootctl install
echo "title ubuntu" >> /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux-zen" >> /boot/loader/entries/arch.conf
echo "initrd /intel-ucode.img" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux-zen.img" >> /boot/loader/entries/arch.conf
echo "options cryptdevice=UUID=$PART_UUID:croot root=/dev/mapper/croot rw" >> /boot/loader/entries/arch.conf

systemctl enable NetworkManager
systemctl enable fstrim.timer

echo "ubuntu" >> /etc/hostname

ln -sf /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime
hwclock --systohc

su - $USERNAME -c 'mkdir ubuntu && cd ubuntu && git clone https://github.com/instantuzer/smp . && stow --no-folding --adopt . && git restore .'

😺
