#!/bin/bash

#sleep 6 

NOTIF_ID=7777

while ! ping -c 1 -W 2 1.1.1.1 &>/dev/null; do
    dunstify -r $NOTIF_ID "pkgs - DNS" "connecting to world..." -u low -i network-offline
    sleep 5
done

dunstctl close $NOTIF_ID

# Get list of updatable packages
pkgs=$(checkupdates 2>/dev/null)

# Count number of packages
if [[ -z "$pkgs" ]]; then
        title="pkgs"
else
        count=$(echo "$pkgs" | wc -l)
	title="pkgs ($count)"
fi

# Set notification message (show packages or a "up to date" message)
# if [ "$count" -eq null ]; then
if [[ -z "$pkgs" ]]; then
    message="uptodate"
    urgence="normal"
else
    message="$pkgs"
    urgence="critical"
fi

# Send notification via dunst
dunstify "$title - DNS" "$message" -u $urgence -i system-software-update

