#!/bin/bash

sleep 600

while true; do
        updates=$(checkupdates 2>/dev/null)
        if [ -n "$updates" ]; then count=$(echo "$updates" | wc -l); dunstify -u low -r 9991 "pkgs ($count)"; fi
    sleep 600
done
