#!/bin/bash

case "$1" in
    # Volume controls
    vol-up)
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
    vol-down)
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
    vol-toggle)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
    # Brightness controls
    bright-up)
        brightnessctl set +8%
        ;;
    bright-down)
        brightnessctl set 8%-
        ;;
    *)
        echo "Usage: $0 {vol-up|vol-down|vol-toggle|bright-up|bright-down}"
        exit 1
        ;;
esac

# --- Notifications ---

# Volume
VOL=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | head -n1)
MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
if [[ "$1" == vol-* ]]; then
    if [ "$MUTED" = "yes" ]; then
        dunstify -u low -r 6666 -t 1000 "Volume: Muted $VOL"
    else
        dunstify -u low -r 6666 -t 1000 "Volume: $VOL"
    fi
fi

# Brightness
if [[ "$1" == bright-* ]]; then
    BRI=$(brightnessctl g)
    MAX=$(brightnessctl m)
    PERCENT=$(( BRI * 100 / MAX ))
    dunstify -u low -r 5555 "Brightness: $PERCENT%"
fi
